#!/usr/bin/env python3
"""
Simple Hello World CGI Script

Minimal CGI script that demonstrates the basic CGI output format:
1. Content-Type header
2. Blank line (CRLF)
3. Body content

This is the simplest possible CGI script.
"""

print("Content-Type: text/html\r")
print("\r")
print("<html>")
print("<head><title>Hello CGI</title></head>")
print("<body>")
print("<h1>Hello from CGI!</h1>")
print("<p>This response was generated by a Python CGI script.</p>")
print("</body>")
print("</html>")
