# Default webserv configuration file
# This file demonstrates all supported directives

server {
	# Listen on all interfaces, port 8080
	listen 8080;

	# Server name for virtual hosting (optional)
	server_name localhost;

	# Custom error pages
	error_page 404 /errors/404.html;
	error_page 500 /errors/500.html;

	# Maximum request body size (1MB)
	client_max_body_size 1M;

	# Default location - serves static files
	# we need POST in order to handle login (cookie demo)
	location / {
		root www;
		index index.html;
		allowed_methods GET POST;
		autoindex off;
	}

	# Static files with directory listing enabled
	location /files {
		root www;
		autoindex on;
		allowed_methods GET;
	}

	# Upload endpoint
	location /uploads {
		root www;
		allowed_methods GET POST DELETE;
		upload_path www/uploads;
		autoindex on;
		client_max_body_size 10M;
	}

	# Python CGI
	location /cgi-bin/py {
		root www;
		allowed_methods GET POST;
		autoindex on;
		cgi_extension .py;
		cgi_pass /usr/bin/python3;
	}

	# Perl CGI
	location /cgi-bin/pl {
		root www;
		allowed_methods GET POST;
		autoindex on;
		cgi_extension .pl;
		cgi_pass /usr/bin/perl;
	}

	# PHP CGI
	location /cgi-bin/php {
		root www;
		allowed_methods GET POST;
		autoindex on;
		cgi_extension .php;
		cgi_pass /usr/bin/php;
	}


	# HTTP redirect example
	location /old-page {
		return 301 /new-page;
	}
}

server {
	# Listen on the SAME port
	listen 8080;          # can be 8080 when virtual hosting is implemented

	# webserver matches the Host header
	server_name marigold.hotel;

	# Use a DIFFERENT root folder or index file
	location / {
		root www/marigold;
		index index.html;
		allowed_methods GET;
	}
}
