worker_processes auto;

events {}

http {
	include /etc/nginx/mime.types;
	default_type  application/octet-stream;

	server {
		listen 8080;
		server_name localhost;

		client_max_body_size 10M;

		error_page 404 /errors/404.html;
		error_page 500 /errors/500.html;

		location / {
			root /mnt/c/Users/dajcs/code/webserv/www;
			index index.html;
		}

		location /files {
			root /mnt/c/Users/dajcs/code/webserv/www;
			autoindex on;
		}

		location /uploads {
			root /mnt/c/Users/dajcs/code/webserv/www;
			autoindex on;
		}

		location /old-page {
			return 301 /new-page;
		}

		location /cgi-bin/py {
			root /mnt/c/Users/dajcs/code/webserv/www/cgi-bin/py;
			fastcgi_pass unix:/run/fcgiwrap.socket;
			include /etc/nginx/fastcgi_params;
		}
	}

	server {
		listen 8080;
		server_name marigold.hotel;

		location / {
			root /mnt/c/Users/dajcs/code/webserv/www/marigold;
			index index.html;
		}
	}
}

# To test:
# sudo nginx -t -c $PWD/config/nginx.conf

# To run:
# sudo nginx -c $PWD/config/nginx.conf

# error 98 - port already in use
# nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Unknown error)
# nginx: [emerg] still could not bind()

# check port usage:
# sudo ss -ltnp | grep :8080
# LISTEN 0      128           0.0.0.0:8080       0.0.0.0:*    users:(("webserv",pid=647654,fd=3))

# check running nginx:
# ps aux | grep nginx

# stop nginx:
# sudo nginx -s stop

# sudo kill <PID>:
# sudo kill 647654

# To reload:
# sudo nginx -s reload -c $PWD/config/nginx.conf

