#!/usr/bin/env python3

"""
Simple Hello World CGI Script

Minimal CGI script that demonstrates the basic CGI output format:
1. Content-Type header
2. Blank line (CRLF)
3. Body content

This is the simplest possible CGI script.
"""

import os

print("Content-Type: text/html\r")
print("\r")
print("<html>")
print("<head><title>Hello CGI</title></head>")
print("<body>")
print("<h1>\"Hello World!\" from Python CGI!</h1>")
print("<p>This response was generated by a Python CGI script `hello.py`</p>")
print("<ul>")
print("<li>", "REQUEST_METHOD =", os.environ.get("REQUEST_METHOD"), "</li>")
print("<li>", "QUERY_STRING =", os.environ.get("QUERY_STRING"), "</li>")
print("</ul>")
print("</body>")
print("</html>")
